export const AuthConstants = {
    JWT_EXPIRATION: '15m',
    REFRESH_TOKEN_EXPIRATION: '7d',
    RESET_TOKEN_EXPIRATION_MS: 3600000, // 1 heure
    MAX_LOGIN_ATTEMPTS: 5,
    LOGIN_ATTEMPTS_TTL_MINUTES: 15,
    BCRYPT_SALT_ROUNDS: 12,
    MAX_SESSION_DURATION_MS: 25 * 60 * 1000, // 25 minutes
};